// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: add_diary_entry_file.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const newDiaryEntryFile = `-- name: NewDiaryEntryFile :one
INSERT INTO diary_files (id, entry_id, file, user_id, created_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW()
)
RETURNING id, created_at, entry_id, file, user_id
`

type NewDiaryEntryFileParams struct {
	EntryID uuid.UUID
	File    string
	UserID  uuid.UUID
}

func (q *Queries) NewDiaryEntryFile(ctx context.Context, arg NewDiaryEntryFileParams) (DiaryFile, error) {
	row := q.db.QueryRowContext(ctx, newDiaryEntryFile, arg.EntryID, arg.File, arg.UserID)
	var i DiaryFile
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EntryID,
		&i.File,
		&i.UserID,
	)
	return i, err
}
