// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: add_diary.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const newDiary = `-- name: NewDiary :one
INSERT INTO diaries (id, alter_id, bg_colour, bg_colour2, block_colour, text_colour, user_id, name)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, alter_id, bg_colour, bg_colour2, block_colour, text_colour, font, user_id, name
`

type NewDiaryParams struct {
	AlterID     uuid.UUID
	BgColour    string
	BlockColour string
	TextColour  string
	UserID      uuid.UUID
	Name        string
}

func (q *Queries) NewDiary(ctx context.Context, arg NewDiaryParams) (Diary, error) {
	row := q.db.QueryRowContext(ctx, newDiary,
		arg.AlterID,
		arg.BgColour,
		arg.BlockColour,
		arg.TextColour,
		arg.UserID,
		arg.Name,
	)
	var i Diary
	err := row.Scan(
		&i.ID,
		&i.AlterID,
		&i.BgColour,
		&i.BgColour2,
		&i.BlockColour,
		&i.TextColour,
		&i.Font,
		&i.UserID,
		&i.Name,
	)
	return i, err
}
