// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: add_friend.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const newFriends = `-- name: NewFriends :exec
INSERT INTO friends (id, request_id, user_id, friend_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3
)
`

type NewFriendsParams struct {
	RequestID uuid.UUID
	UserID    uuid.UUID
	FriendID  uuid.UUID
}

func (q *Queries) NewFriends(ctx context.Context, arg NewFriendsParams) error {
	_, err := q.db.ExecContext(ctx, newFriends, arg.RequestID, arg.UserID, arg.FriendID)
	return err
}
