// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alters_delete.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteAlter = `-- name: DeleteAlter :exec
DELETE FROM alters
WHERE id = $1
`

func (q *Queries) DeleteAlter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAlter, id)
	return err
}
