// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alters_add.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAlter = `-- name: CreateAlter :one
INSERT INTO alters (id, created_at, updated_at, avatar, name, pronouns, age, alter_role, description, colour, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING  id, created_at, updated_at, avatar, name, pronouns, age, alter_role, description, colour, fronting, fronting_since, user_id
`

type CreateAlterParams struct {
	Avatar      string
	Name        string
	Pronouns    string
	Age         string
	AlterRole   string
	Description string
	Colour      string
	UserID      uuid.UUID
}

func (q *Queries) CreateAlter(ctx context.Context, arg CreateAlterParams) (Alter, error) {
	row := q.db.QueryRowContext(ctx, createAlter,
		arg.Avatar,
		arg.Name,
		arg.Pronouns,
		arg.Age,
		arg.AlterRole,
		arg.Description,
		arg.Colour,
		arg.UserID,
	)
	var i Alter
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Name,
		&i.Pronouns,
		&i.Age,
		&i.AlterRole,
		&i.Description,
		&i.Colour,
		&i.Fronting,
		&i.FrontingSince,
		&i.UserID,
	)
	return i, err
}
