// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alters_avatar_edit.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const editAlterAvatar = `-- name: EditAlterAvatar :one
UPDATE alters
SET avatar = $3
WHERE id = $1 and user_id = $2
RETURNING id, created_at, updated_at, avatar, name, pronouns, age, alter_role, description, colour, fronting, fronting_since, user_id
`

type EditAlterAvatarParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Avatar string
}

func (q *Queries) EditAlterAvatar(ctx context.Context, arg EditAlterAvatarParams) (Alter, error) {
	row := q.db.QueryRowContext(ctx, editAlterAvatar, arg.ID, arg.UserID, arg.Avatar)
	var i Alter
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Name,
		&i.Pronouns,
		&i.Age,
		&i.AlterRole,
		&i.Description,
		&i.Colour,
		&i.Fronting,
		&i.FrontingSince,
		&i.UserID,
	)
	return i, err
}
