// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alters_edit.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const editAlter = `-- name: EditAlter :one
UPDATE alters
SET name = $3,
pronouns = $4,
age = $5,
alter_role = $6,
description = $7, 
colour = $8
WHERE id = $1 and user_id = $2
RETURNING id, created_at, updated_at, avatar, name, pronouns, age, alter_role, description, colour, fronting, fronting_since, user_id
`

type EditAlterParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Pronouns    string
	Age         string
	AlterRole   string
	Description string
	Colour      string
}

func (q *Queries) EditAlter(ctx context.Context, arg EditAlterParams) (Alter, error) {
	row := q.db.QueryRowContext(ctx, editAlter,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Pronouns,
		arg.Age,
		arg.AlterRole,
		arg.Description,
		arg.Colour,
	)
	var i Alter
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Name,
		&i.Pronouns,
		&i.Age,
		&i.AlterRole,
		&i.Description,
		&i.Colour,
		&i.Fronting,
		&i.FrontingSince,
		&i.UserID,
	)
	return i, err
}
