// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: answer_request.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const answerFriendRequest = `-- name: AnswerFriendRequest :one
UPDATE requests
SET answer = $1
WHERE receiver_id = $2 and id = $3
RETURNING id, created_at, expires_at, sender_id, receiver_id, answer
`

type AnswerFriendRequestParams struct {
	Answer     int32
	ReceiverID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) AnswerFriendRequest(ctx context.Context, arg AnswerFriendRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, answerFriendRequest, arg.Answer, arg.ReceiverID, arg.ID)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SenderID,
		&i.ReceiverID,
		&i.Answer,
	)
	return i, err
}
