// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_fornewbies.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const newForNewbies = `-- name: NewForNewbies :one
INSERT INTO for_newbies (id, user_id, text)
VALUES (
    gen_random_uuid(),
    $1,
    $2
)
RETURNING id, user_id, text
`

type NewForNewbiesParams struct {
	UserID uuid.UUID
	Text   string
}

func (q *Queries) NewForNewbies(ctx context.Context, arg NewForNewbiesParams) (ForNewby, error) {
	row := q.db.QueryRowContext(ctx, newForNewbies, arg.UserID, arg.Text)
	var i ForNewby
	err := row.Scan(&i.ID, &i.UserID, &i.Text)
	return i, err
}
