// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_diary_entry.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteDiaryEntry = `-- name: DeleteDiaryEntry :exec
DELETE FROM diary_entries WHERE id = $1 and user_id = $2
`

type DeleteDiaryEntryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteDiaryEntry(ctx context.Context, arg DeleteDiaryEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteDiaryEntry, arg.ID, arg.UserID)
	return err
}
