// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_friends.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteFriendRequest = `-- name: DeleteFriendRequest :exec
DELETE FROM requests WHERE id = $1
`

func (q *Queries) DeleteFriendRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFriendRequest, id)
	return err
}
