// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_diary.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteDiary = `-- name: DeleteDiary :exec
DELETE FROM diaries WHERE id = $1 and user_id = $2
`

type DeleteDiaryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteDiary(ctx context.Context, arg DeleteDiaryParams) error {
	_, err := q.db.ExecContext(ctx, deleteDiary, arg.ID, arg.UserID)
	return err
}
