// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_diary_entry_file.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteDiaryEntryFile = `-- name: DeleteDiaryEntryFile :exec
DELETE FROM diary_files WHERE id = $1 and user_id = $2
`

type DeleteDiaryEntryFileParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteDiaryEntryFile(ctx context.Context, arg DeleteDiaryEntryFileParams) error {
	_, err := q.db.ExecContext(ctx, deleteDiaryEntryFile, arg.ID, arg.UserID)
	return err
}
