// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edit_user_avatar.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const editUserAvatar = `-- name: EditUserAvatar :one
UPDATE users
SET
avatar = $1
WHERE id = $2
RETURNING id, created_at, updated_at, email, hashed_password, avatar, system_name, theme, font
`

type EditUserAvatarParams struct {
	Avatar string
	ID     uuid.UUID
}

func (q *Queries) EditUserAvatar(ctx context.Context, arg EditUserAvatarParams) (User, error) {
	row := q.db.QueryRowContext(ctx, editUserAvatar, arg.Avatar, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.Avatar,
		&i.SystemName,
		&i.Theme,
		&i.Font,
	)
	return i, err
}
