// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edit_fornewbies.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const editForNewbies = `-- name: EditForNewbies :one
UPDATE for_newbies
SET text = $1
WHERE user_id = $2
RETURNING id, user_id, text
`

type EditForNewbiesParams struct {
	Text   string
	UserID uuid.UUID
}

func (q *Queries) EditForNewbies(ctx context.Context, arg EditForNewbiesParams) (ForNewby, error) {
	row := q.db.QueryRowContext(ctx, editForNewbies, arg.Text, arg.UserID)
	var i ForNewby
	err := row.Scan(&i.ID, &i.UserID, &i.Text)
	return i, err
}
