// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edit_diary_entry.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const editDiaryEntry = `-- name: EditDiaryEntry :one
UPDATE diary_entries
SET name = $1, 
text = $2
WHERE id = $3 and user_id = $4
RETURNING id, diary_id, name, date, text, user_id
`

type EditDiaryEntryParams struct {
	Name   string
	Text   string
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) EditDiaryEntry(ctx context.Context, arg EditDiaryEntryParams) (DiaryEntry, error) {
	row := q.db.QueryRowContext(ctx, editDiaryEntry,
		arg.Name,
		arg.Text,
		arg.ID,
		arg.UserID,
	)
	var i DiaryEntry
	err := row.Scan(
		&i.ID,
		&i.DiaryID,
		&i.Name,
		&i.Date,
		&i.Text,
		&i.UserID,
	)
	return i, err
}
