// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edit_userinfo_settings.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const editUserSettings = `-- name: EditUserSettings :one
UPDATE users
SET
system_name = $1,
theme = $2,
font = $3  
WHERE id = $4
RETURNING id, created_at, updated_at, email, hashed_password, avatar, system_name, theme, font
`

type EditUserSettingsParams struct {
	SystemName string
	Theme      int32
	Font       string
	ID         uuid.UUID
}

func (q *Queries) EditUserSettings(ctx context.Context, arg EditUserSettingsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, editUserSettings,
		arg.SystemName,
		arg.Theme,
		arg.Font,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.Avatar,
		&i.SystemName,
		&i.Theme,
		&i.Font,
	)
	return i, err
}
