// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edit_diary.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const editDiary = `-- name: EditDiary :one
UPDATE diaries
SET bg_colour = $1,
bg_colour2 = $2, 
block_colour = $3,
text_colour = $4,
font = $5
WHERE id = $6 and user_id = $7
RETURNING id, alter_id, bg_colour, bg_colour2, block_colour, text_colour, font, user_id, name
`

type EditDiaryParams struct {
	BgColour    string
	BgColour2   string
	BlockColour string
	TextColour  string
	Font        string
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) EditDiary(ctx context.Context, arg EditDiaryParams) (Diary, error) {
	row := q.db.QueryRowContext(ctx, editDiary,
		arg.BgColour,
		arg.BgColour2,
		arg.BlockColour,
		arg.TextColour,
		arg.Font,
		arg.ID,
		arg.UserID,
	)
	var i Diary
	err := row.Scan(
		&i.ID,
		&i.AlterID,
		&i.BgColour,
		&i.BgColour2,
		&i.BlockColour,
		&i.TextColour,
		&i.Font,
		&i.UserID,
		&i.Name,
	)
	return i, err
}
