// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edit_userinfo.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const editUserInfo = `-- name: EditUserInfo :one
UPDATE users
SET email = $1, 
hashed_password = $2,

system_name = $3,
theme = $4,
font = $5  
WHERE id = $6
RETURNING id, created_at, updated_at, email, hashed_password, avatar, system_name, theme, font
`

type EditUserInfoParams struct {
	Email          string
	HashedPassword string
	SystemName     string
	Theme          int32
	Font           string
	ID             uuid.UUID
}

func (q *Queries) EditUserInfo(ctx context.Context, arg EditUserInfoParams) (User, error) {
	row := q.db.QueryRowContext(ctx, editUserInfo,
		arg.Email,
		arg.HashedPassword,
		arg.SystemName,
		arg.Theme,
		arg.Font,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.Avatar,
		&i.SystemName,
		&i.Theme,
		&i.Font,
	)
	return i, err
}
