// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: end_front.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const endFrontFronts = `-- name: EndFrontFronts :exec
UPDATE fronts
SET ended_at = NOW()
WHERE Id = $1 and ended_at IS NULL
`

func (q *Queries) EndFrontFronts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, endFrontFronts, id)
	return err
}
