// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: find_friend_request.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFriendRequest = `-- name: GetFriendRequest :one
SELECT id, created_at, expires_at, sender_id, receiver_id, answer FROM requests WHERE (receiver_id = $1 and sender_id = $2) or (receiver_id = $2 and sender_id = $1)
`

type GetFriendRequestParams struct {
	ReceiverID uuid.UUID
	SenderID   uuid.UUID
}

func (q *Queries) GetFriendRequest(ctx context.Context, arg GetFriendRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, getFriendRequest, arg.ReceiverID, arg.SenderID)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SenderID,
		&i.ReceiverID,
		&i.Answer,
	)
	return i, err
}
