// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_all_friends.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAllFriends = `-- name: GetAllFriends :many
SELECT users.id, created_at, updated_at, email, hashed_password, avatar, system_name, theme, font, friends.id, request_id, user_id, friend_id FROM users JOIN friends
ON users.id = friends.friend_id
WHERE friends.user_id = $1
`

type GetAllFriendsRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	Avatar         string
	SystemName     string
	Theme          int32
	Font           string
	ID_2           uuid.UUID
	RequestID      uuid.UUID
	UserID         uuid.UUID
	FriendID       uuid.UUID
}

func (q *Queries) GetAllFriends(ctx context.Context, userID uuid.UUID) ([]GetAllFriendsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFriendsRow
	for rows.Next() {
		var i GetAllFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.HashedPassword,
			&i.Avatar,
			&i.SystemName,
			&i.Theme,
			&i.Font,
			&i.ID_2,
			&i.RequestID,
			&i.UserID,
			&i.FriendID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
