// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_if_friends.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getIfFriends = `-- name: GetIfFriends :one
SELECT id, request_id, user_id, friend_id FROM friends WHERE user_id = $1 and friend_id = $2
`

type GetIfFriendsParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) GetIfFriends(ctx context.Context, arg GetIfFriendsParams) (Friend, error) {
	row := q.db.QueryRowContext(ctx, getIfFriends, arg.UserID, arg.FriendID)
	var i Friend
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.FriendID,
	)
	return i, err
}
