// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_alters_without_diaries.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAltersWithoutDiaries = `-- name: GetAltersWithoutDiaries :many
SELECT alters.id, alters.created_at, alters.updated_at, alters.avatar, alters.name, alters.pronouns, alters.age, alters.alter_role, alters.description, alters.colour, alters.fronting, alters.fronting_since, alters.user_id FROM alters
WHERE alters.user_id = $1 and alters.id not in(SELECT alter_id FROM diaries)
ORDER BY alters.created_at ASC
`

func (q *Queries) GetAltersWithoutDiaries(ctx context.Context, userID uuid.UUID) ([]Alter, error) {
	rows, err := q.db.QueryContext(ctx, getAltersWithoutDiaries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alter
	for rows.Next() {
		var i Alter
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Avatar,
			&i.Name,
			&i.Pronouns,
			&i.Age,
			&i.AlterRole,
			&i.Description,
			&i.Colour,
			&i.Fronting,
			&i.FrontingSince,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
