// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_requests_receiver.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getNewFriendRequestsReciever = `-- name: GetNewFriendRequestsReciever :many

SELECT users.id, users.created_at, users.updated_at, users.email, users.hashed_password, users.avatar, users.system_name, users.theme, users.font, requests.id, requests.answer FROM requests
JOIN users ON requests.sender_id=users.id
WHERE requests.receiver_id = $1 and requests.answer = 0
`

type GetNewFriendRequestsRecieverRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	Avatar         string
	SystemName     string
	Theme          int32
	Font           string
	ID_2           uuid.UUID
	Answer         int32
}

func (q *Queries) GetNewFriendRequestsReciever(ctx context.Context, receiverID uuid.UUID) ([]GetNewFriendRequestsRecieverRow, error) {
	rows, err := q.db.QueryContext(ctx, getNewFriendRequestsReciever, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNewFriendRequestsRecieverRow
	for rows.Next() {
		var i GetNewFriendRequestsRecieverRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.HashedPassword,
			&i.Avatar,
			&i.SystemName,
			&i.Theme,
			&i.Font,
			&i.ID_2,
			&i.Answer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
