// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_for_newbies.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getForNewbies = `-- name: GetForNewbies :one
SELECT id, user_id, text FROM for_newbies WHERE user_id = $1
`

func (q *Queries) GetForNewbies(ctx context.Context, userID uuid.UUID) (ForNewby, error) {
	row := q.db.QueryRowContext(ctx, getForNewbies, userID)
	var i ForNewby
	err := row.Scan(&i.ID, &i.UserID, &i.Text)
	return i, err
}
