// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_diary.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getDiary = `-- name: GetDiary :one
SELECT id, alter_id, bg_colour, bg_colour2, block_colour, text_colour, font, user_id, name FROM diaries 
WHERE id = $1 and user_id = $2
`

type GetDiaryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetDiary(ctx context.Context, arg GetDiaryParams) (Diary, error) {
	row := q.db.QueryRowContext(ctx, getDiary, arg.ID, arg.UserID)
	var i Diary
	err := row.Scan(
		&i.ID,
		&i.AlterID,
		&i.BgColour,
		&i.BgColour2,
		&i.BlockColour,
		&i.TextColour,
		&i.Font,
		&i.UserID,
		&i.Name,
	)
	return i, err
}
