// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_fronts_by_time.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getFrontsByTime = `-- name: GetFrontsByTime :many
SELECT fronts.id, started_at, ended_at, alter_id, alters.id, created_at, updated_at, avatar, name, pronouns, age, alter_role, description, colour, fronting, fronting_since, user_id
FROM fronts JOIN alters ON fronts.alter_id = alters.id
WHERE alters.user_id = $3 and ((fronts.started_at between $1 and $2) or (fronts.ended_at between $1 and $2)
or (fronts.started_at < $1 and(fronts.ended_at IS NULL or fronts.ended_at > $2)))
`

type GetFrontsByTimeParams struct {
	StartedAt   time.Time
	StartedAt_2 time.Time
	UserID      uuid.UUID
}

type GetFrontsByTimeRow struct {
	ID            uuid.UUID
	StartedAt     time.Time
	EndedAt       sql.NullTime
	AlterID       uuid.UUID
	ID_2          uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Avatar        string
	Name          string
	Pronouns      string
	Age           string
	AlterRole     string
	Description   string
	Colour        string
	Fronting      bool
	FrontingSince sql.NullTime
	UserID        uuid.UUID
}

func (q *Queries) GetFrontsByTime(ctx context.Context, arg GetFrontsByTimeParams) ([]GetFrontsByTimeRow, error) {
	rows, err := q.db.QueryContext(ctx, getFrontsByTime, arg.StartedAt, arg.StartedAt_2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFrontsByTimeRow
	for rows.Next() {
		var i GetFrontsByTimeRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.EndedAt,
			&i.AlterID,
			&i.ID_2,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Avatar,
			&i.Name,
			&i.Pronouns,
			&i.Age,
			&i.AlterRole,
			&i.Description,
			&i.Colour,
			&i.Fronting,
			&i.FrontingSince,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
