// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_diary_by_alter.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getDiaryByALter = `-- name: GetDiaryByALter :one
SELECT id, alter_id, bg_colour, bg_colour2, block_colour, text_colour, font, user_id, name FROM diaries 
WHERE alter_id = $1 and user_id = $2
`

type GetDiaryByALterParams struct {
	AlterID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetDiaryByALter(ctx context.Context, arg GetDiaryByALterParams) (Diary, error) {
	row := q.db.QueryRowContext(ctx, getDiaryByALter, arg.AlterID, arg.UserID)
	var i Diary
	err := row.Scan(
		&i.ID,
		&i.AlterID,
		&i.BgColour,
		&i.BgColour2,
		&i.BlockColour,
		&i.TextColour,
		&i.Font,
		&i.UserID,
		&i.Name,
	)
	return i, err
}
