// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_diary_entry_files_by_entry.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getDiaryEntryFilesByEntry = `-- name: GetDiaryEntryFilesByEntry :many
SELECT id, created_at, entry_id, file, user_id FROM diary_files WHERE entry_id = $1 and user_id = $2
`

type GetDiaryEntryFilesByEntryParams struct {
	EntryID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetDiaryEntryFilesByEntry(ctx context.Context, arg GetDiaryEntryFilesByEntryParams) ([]DiaryFile, error) {
	rows, err := q.db.QueryContext(ctx, getDiaryEntryFilesByEntry, arg.EntryID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiaryFile
	for rows.Next() {
		var i DiaryFile
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.EntryID,
			&i.File,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
