// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_diary_entry.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getDiaryEntry = `-- name: GetDiaryEntry :one
SELECT id, diary_id, name, date, text, user_id FROM diary_entries WHERE id = $1 and user_id = $2
`

type GetDiaryEntryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetDiaryEntry(ctx context.Context, arg GetDiaryEntryParams) (DiaryEntry, error) {
	row := q.db.QueryRowContext(ctx, getDiaryEntry, arg.ID, arg.UserID)
	var i DiaryEntry
	err := row.Scan(
		&i.ID,
		&i.DiaryID,
		&i.Name,
		&i.Date,
		&i.Text,
		&i.UserID,
	)
	return i, err
}
