// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_diary_entry_file.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getDiaryEntryFile = `-- name: GetDiaryEntryFile :one
SELECT id, created_at, entry_id, file, user_id FROM diary_files WHERE id = $1 and user_id = $2
`

type GetDiaryEntryFileParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetDiaryEntryFile(ctx context.Context, arg GetDiaryEntryFileParams) (DiaryFile, error) {
	row := q.db.QueryRowContext(ctx, getDiaryEntryFile, arg.ID, arg.UserID)
	var i DiaryFile
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EntryID,
		&i.File,
		&i.UserID,
	)
	return i, err
}
