// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_front.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getNowFrontByAlter = `-- name: GetNowFrontByAlter :one
SELECT id, started_at, ended_at, alter_id FROM fronts WHERE alter_id = $1 and ended_at IS NULL
`

func (q *Queries) GetNowFrontByAlter(ctx context.Context, alterID uuid.UUID) (Front, error) {
	row := q.db.QueryRowContext(ctx, getNowFrontByAlter, alterID)
	var i Front
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.EndedAt,
		&i.AlterID,
	)
	return i, err
}
