// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_diaries.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getDiaries = `-- name: GetDiaries :many
SELECT diaries.id, diaries.alter_id, diaries.bg_colour, diaries.bg_colour2, diaries.block_colour, diaries.text_colour, diaries.font, diaries.user_id, diaries.name, alters.avatar FROM diaries join alters on diaries.alter_id = alters.id 
WHERE diaries.user_id = $1
`

type GetDiariesRow struct {
	ID          uuid.UUID
	AlterID     uuid.UUID
	BgColour    string
	BgColour2   string
	BlockColour string
	TextColour  string
	Font        string
	UserID      uuid.UUID
	Name        string
	Avatar      string
}

func (q *Queries) GetDiaries(ctx context.Context, userID uuid.UUID) ([]GetDiariesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDiaries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDiariesRow
	for rows.Next() {
		var i GetDiariesRow
		if err := rows.Scan(
			&i.ID,
			&i.AlterID,
			&i.BgColour,
			&i.BgColour2,
			&i.BlockColour,
			&i.TextColour,
			&i.Font,
			&i.UserID,
			&i.Name,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
