// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_diary_entries.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getDiaryEntriesByDiary = `-- name: GetDiaryEntriesByDiary :many
SELECT id, diary_id, name, date, text, user_id FROM diary_entries WHERE diary_id = $1 and user_id = $2
`

type GetDiaryEntriesByDiaryParams struct {
	DiaryID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetDiaryEntriesByDiary(ctx context.Context, arg GetDiaryEntriesByDiaryParams) ([]DiaryEntry, error) {
	rows, err := q.db.QueryContext(ctx, getDiaryEntriesByDiary, arg.DiaryID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiaryEntry
	for rows.Next() {
		var i DiaryEntry
		if err := rows.Scan(
			&i.ID,
			&i.DiaryID,
			&i.Name,
			&i.Date,
			&i.Text,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
