// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_alters_by_author.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAltersByAuthor = `-- name: GetAltersByAuthor :many
SELECT id, created_at, updated_at, avatar, name, pronouns, age, alter_role, description, colour, fronting, fronting_since, user_id FROM alters
WHERE user_id = $1 and LOWER(name) LIKE $2
ORDER BY created_at ASC
`

type GetAltersByAuthorParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) GetAltersByAuthor(ctx context.Context, arg GetAltersByAuthorParams) ([]Alter, error) {
	rows, err := q.db.QueryContext(ctx, getAltersByAuthor, arg.UserID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alter
	for rows.Next() {
		var i Alter
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Avatar,
			&i.Name,
			&i.Pronouns,
			&i.Age,
			&i.AlterRole,
			&i.Description,
			&i.Colour,
			&i.Fronting,
			&i.FrontingSince,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
