// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Alter struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Avatar        string
	Name          string
	Pronouns      string
	Age           string
	AlterRole     string
	Description   string
	Colour        string
	Fronting      bool
	FrontingSince sql.NullTime
	UserID        uuid.UUID
}

type Diary struct {
	ID          uuid.UUID
	AlterID     uuid.UUID
	BgColour    string
	BgColour2   string
	BlockColour string
	TextColour  string
	Font        string
	UserID      uuid.UUID
	Name        string
}

type DiaryEntry struct {
	ID      uuid.UUID
	DiaryID uuid.UUID
	Name    string
	Date    time.Time
	Text    string
	UserID  uuid.UUID
}

type DiaryFile struct {
	ID        uuid.UUID
	CreatedAt time.Time
	EntryID   uuid.UUID
	File      string
	UserID    uuid.UUID
}

type ForNewby struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Text   string
}

type Friend struct {
	ID        uuid.UUID
	RequestID uuid.UUID
	UserID    uuid.UUID
	FriendID  uuid.UUID
}

type Front struct {
	ID        uuid.UUID
	StartedAt time.Time
	EndedAt   sql.NullTime
	AlterID   uuid.UUID
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Request struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  sql.NullTime
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
	Answer     int32
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	Avatar         string
	SystemName     string
	Theme          int32
	Font           string
}
