// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: new_friend_request.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const newFriendRequest = `-- name: NewFriendRequest :one
INSERT INTO requests (id, created_at, sender_id, receiver_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, expires_at, sender_id, receiver_id, answer
`

type NewFriendRequestParams struct {
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
}

func (q *Queries) NewFriendRequest(ctx context.Context, arg NewFriendRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, newFriendRequest, arg.SenderID, arg.ReceiverID)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SenderID,
		&i.ReceiverID,
		&i.Answer,
	)
	return i, err
}
