// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: new_front_alter.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const newFrontAlter = `-- name: NewFrontAlter :one
UPDATE alters
SET fronting = true, fronting_since = (NOW() at time zone 'utc')
WHERE id = $1
RETURNING id, created_at, updated_at, avatar, name, pronouns, age, alter_role, description, colour, fronting, fronting_since, user_id
`

func (q *Queries) NewFrontAlter(ctx context.Context, id uuid.UUID) (Alter, error) {
	row := q.db.QueryRowContext(ctx, newFrontAlter, id)
	var i Alter
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Avatar,
		&i.Name,
		&i.Pronouns,
		&i.Age,
		&i.AlterRole,
		&i.Description,
		&i.Colour,
		&i.Fronting,
		&i.FrontingSince,
		&i.UserID,
	)
	return i, err
}
