// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: new_front.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const newFront = `-- name: NewFront :exec
INSERT INTO fronts (id, started_at, alter_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    $1
)
`

func (q *Queries) NewFront(ctx context.Context, alterID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, newFront, alterID)
	return err
}
