// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: new_diary_entry.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const newDiaryEntry = `-- name: NewDiaryEntry :one
INSERT INTO diary_entries (id, diary_id, name, date, text, user_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    (NOW() at time zone 'utc'),
    $3,
    $4
)
RETURNING id, diary_id, name, date, text, user_id
`

type NewDiaryEntryParams struct {
	DiaryID uuid.UUID
	Name    string
	Text    string
	UserID  uuid.UUID
}

func (q *Queries) NewDiaryEntry(ctx context.Context, arg NewDiaryEntryParams) (DiaryEntry, error) {
	row := q.db.QueryRowContext(ctx, newDiaryEntry,
		arg.DiaryID,
		arg.Name,
		arg.Text,
		arg.UserID,
	)
	var i DiaryEntry
	err := row.Scan(
		&i.ID,
		&i.DiaryID,
		&i.Name,
		&i.Date,
		&i.Text,
		&i.UserID,
	)
	return i, err
}
