// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_create.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_password, avatar, system_name, theme, font)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING  id, created_at, updated_at, email, hashed_password, avatar, system_name, theme, font
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
	Avatar         string
	SystemName     string
	Theme          int32
	Font           string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.HashedPassword,
		arg.Avatar,
		arg.SystemName,
		arg.Theme,
		arg.Font,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.Avatar,
		&i.SystemName,
		&i.Theme,
		&i.Font,
	)
	return i, err
}
